### ISSUE TITLE
where is my virtual girlfriemd

### ISSUE THREAD

**Issue by Tacocat4642** [JakeGuy11/vcast-data#1]
Today I woke up in my mountain dew stained bed, opened my favorite subreddit, r/hololive, and realized: today is the day. It’s the day that the fictional women would play my favorite video game! I rolled out of bed, and after struggling to get up, I turned on my computer, breathing heavily. This was the most exercise I’d done in a while. I loaded up my computer and opened Twitch, and entered the stream, gazing at the fictional women on the screen, reking all the idiot real people in the game. It was beautiful. But then, disaster struck. It appears the VTuber software crashed, because the hot fictional women’s facecam now showed a balding middle aged man! I vomited all over the screen, feeling weak. How could this be? The fictional women were fabrications this whole time? I sadly chugged my entire 12 pack of mountain dew, and cried myself to sleep.

**Comment by JakeGuy11** [comment]
implementation error, check your dependencies
